menu:
  Home: /
  Archives: /archives

widgets:
# - search
- category
# - tag
# - tagcloud
# - twitter

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

github: mrgamer
email: valerio.coltre@gmail.com
about: "Grumpy developer from Rome, messing with technology"
photo:
  - https://en.gravatar.com/userimage/42435845/782568548e458a2ff3058a0f46e0fa01.png?size=200
  - https://en.gravatar.com/userimage/42435845/c495d5cc01ed37b5d82be67415b0d5dd.jpg?size=200
  - https://en.gravatar.com/userimage/42435845/acbbe5812de9a2c6807e98d6f6ce039d.jpg?size=200
  - http://blogs.kcrw.com/pressplay/wp-content/uploads/2014/01/Grumpy-Cat1.jpg
  - http://sms111.org/wallpapers/wp-content/uploads/2013/06/Grumpy-Cat-Cute.jpg
  - http://fc06.deviantart.net/fs70/i/2013/013/2/c/grumpy_cat_by_adlynh-d5rdjjr.png

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: false

fancybox: true

google_analytics: UA-42587136-2
rss: false
